<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<div class="ms-page-head"><div><h1>Expenses</h1><p>Rent, delivery, repairs, procurement and operating costs that feed profit reporting.</p></div><button class="ms-btn ms-btn-primary" type="button" data-open-dialog="expenseDialog">+ Add Expense</button></div>
<div class="ms-search ms-spacer-bottom"><input class="ms-input" data-table-filter="#expenseTable" placeholder="Search expense, payee or reference"></div>
<div class="ms-table-scroll"><table class="ms-table" id="expenseTable"><thead><tr><th>Date</th><th>Category</th><th>Payee</th><th>Reference</th><th>Notes</th><th>Amount</th><th>Action</th></tr></thead><tbody>
<?php foreach ($expenses as $e): ?><tr><td><?= esc($e['expense_date']) ?></td><td><strong><?= esc($e['category']) ?></strong></td><td><?= esc($e['payee'] ?? '-') ?></td><td><?= esc($e['reference_no'] ?? '-') ?></td><td><?= esc($e['notes'] ?? '-') ?></td><td><strong>₹<?= number_format((float) $e['amount'], 2) ?></strong></td><td><button class="ms-btn ms-btn-secondary is-sm" type="button" data-open-dialog="editExpense<?= (int) $e['id'] ?>">Edit</button></td></tr><?php endforeach; ?>
<?php if (! $expenses): ?><tr><td colspan="7" class="ms-empty ms-no-filter">No expenses recorded.</td></tr><?php endif; ?>
</tbody></table></div>
<?php foreach ($expenses as $e): ?><dialog id="editExpense<?= (int) $e['id'] ?>"><div class="ms-dialog-body"><div class="ms-dialog-head"><h3>Edit expense</h3><button type="button" class="ms-btn ms-btn-secondary is-sm" data-close-dialog>Close</button></div><form method="post" action="<?= site_url('expenses/' . $e['id']) ?>"><?= csrf_field() ?><div class="ms-form-grid"><div class="ms-field"><label>Date</label><input class="ms-input" type="date" name="expense_date" value="<?= esc($e['expense_date']) ?>"></div><div class="ms-field"><label>Category *</label><input class="ms-input" name="category" required value="<?= esc($e['category']) ?>"></div><div class="ms-field"><label>Amount *</label><input class="ms-input" type="number" min="0.01" step="0.01" name="amount" required value="<?= esc($e['amount']) ?>"></div><div class="ms-field"><label>Payee</label><input class="ms-input" name="payee" value="<?= esc($e['payee'] ?? '') ?>"></div><div class="ms-field"><label>Reference</label><input class="ms-input" name="reference_no" value="<?= esc($e['reference_no'] ?? '') ?>"></div><div class="ms-field ms-full"><label>Notes</label><textarea class="ms-textarea" name="notes"><?= esc($e['notes'] ?? '') ?></textarea></div><div class="ms-field ms-full"><button class="ms-btn ms-btn-primary">Save Expense</button></div></div></form></div></dialog><?php endforeach; ?>
<dialog id="expenseDialog"><div class="ms-dialog-body"><div class="ms-dialog-head"><h3>Add expense</h3><button type="button" class="ms-btn ms-btn-secondary is-sm" data-close-dialog>Close</button></div><form method="post" action="<?= site_url('expenses') ?>"><?= csrf_field() ?><div class="ms-form-grid"><div class="ms-field"><label>Date</label><input class="ms-input" type="date" name="expense_date" value="<?= date('Y-m-d') ?>"></div><div class="ms-field"><label>Category *</label><input class="ms-input" name="category" required placeholder="Rent / Delivery / Procurement"></div><div class="ms-field"><label>Amount *</label><input class="ms-input" type="number" min="0.01" step="0.01" name="amount" required></div><div class="ms-field"><label>Payee</label><input class="ms-input" name="payee"></div><div class="ms-field"><label>Reference</label><input class="ms-input" name="reference_no"></div><div class="ms-field ms-full"><label>Notes</label><textarea class="ms-textarea" name="notes"></textarea></div><div class="ms-field ms-full"><button class="ms-btn ms-btn-primary">Save Expense</button></div></div></form></div></dialog>
<?= $this->endSection() ?>
