<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<div class="ms-page-head"><div><h1>Suppliers & source stores</h1><p>Vendors, other mobile shops and individuals you buy or borrow stock from.</p></div><button class="ms-btn ms-btn-primary" type="button" data-open-dialog="supplierDialog">+ Add Supplier</button></div>
<div class="ms-search ms-spacer-bottom"><input class="ms-input" data-table-filter="#supplierTable" placeholder="Search supplier, store, phone or GSTIN"></div>
<div class="ms-table-scroll"><table class="ms-table" id="supplierTable"><thead><tr><th>Name</th><th>Type</th><th>Phone</th><th>Email</th><th>GSTIN</th><th>Address</th><th>Action</th></tr></thead><tbody>
<?php foreach ($rows as $s): ?><tr><td><strong><?= esc($s['name']) ?></strong></td><td><span class="ms-badge <?= $s['supplier_type'] === 'other_store' ? 'is-warn' : '' ?>"><?= esc(ucwords(str_replace('_', ' ', $s['supplier_type']))) ?></span></td><td><?= esc($s['phone'] ?? '-') ?></td><td><?= esc($s['email'] ?? '-') ?></td><td><?= esc($s['gstin'] ?? '-') ?></td><td><?= esc($s['address'] ?? '-') ?></td><td><button class="ms-btn ms-btn-secondary is-sm" type="button" data-open-dialog="editSupplier<?= (int) $s['id'] ?>">Edit</button></td></tr><?php endforeach; ?>
<?php if (! $rows): ?><tr><td colspan="7" class="ms-empty ms-no-filter">No suppliers or source stores yet.</td></tr><?php endif; ?>
</tbody></table></div>
<?php foreach ($rows as $s): ?><dialog id="editSupplier<?= (int) $s['id'] ?>"><div class="ms-dialog-body"><div class="ms-dialog-head"><h3>Edit supplier/source</h3><button class="ms-btn ms-btn-secondary is-sm" type="button" data-close-dialog>Close</button></div><form method="post" action="<?= site_url('suppliers/' . $s['id']) ?>"><?= csrf_field() ?><div class="ms-form-grid"><div class="ms-field"><label>Name *</label><input class="ms-input" name="name" required value="<?= esc($s['name']) ?>"></div><div class="ms-field"><label>Type</label><select class="ms-select" name="supplier_type"><?php foreach (['vendor' => 'Vendor', 'other_store' => 'Other Store', 'individual' => 'Individual'] as $v => $l): ?><option value="<?= $v ?>" <?= $s['supplier_type'] === $v ? 'selected' : '' ?>><?= $l ?></option><?php endforeach; ?></select></div><div class="ms-field"><label>Phone</label><input class="ms-input" name="phone" value="<?= esc($s['phone'] ?? '') ?>"></div><div class="ms-field"><label>Email</label><input class="ms-input" type="email" name="email" value="<?= esc($s['email'] ?? '') ?>"></div><div class="ms-field"><label>GSTIN</label><input class="ms-input" name="gstin" value="<?= esc($s['gstin'] ?? '') ?>"></div><div class="ms-field ms-full"><label>Address</label><textarea class="ms-textarea" name="address"><?= esc($s['address'] ?? '') ?></textarea></div><div class="ms-field ms-full"><button class="ms-btn ms-btn-primary">Save Changes</button></div></div></form></div></dialog><?php endforeach; ?>
<dialog id="supplierDialog"><div class="ms-dialog-body"><div class="ms-dialog-head"><h3>Add supplier/source</h3><button class="ms-btn ms-btn-secondary is-sm" type="button" data-close-dialog>Close</button></div><form method="post" action="<?= site_url('suppliers') ?>"><?= csrf_field() ?><div class="ms-form-grid"><div class="ms-field"><label>Name *</label><input class="ms-input" name="name" required></div><div class="ms-field"><label>Type</label><select class="ms-select" name="supplier_type"><option value="vendor">Vendor</option><option value="other_store">Other Store</option><option value="individual">Individual</option></select></div><div class="ms-field"><label>Phone</label><input class="ms-input" name="phone"></div><div class="ms-field"><label>Email</label><input class="ms-input" type="email" name="email"></div><div class="ms-field"><label>GSTIN</label><input class="ms-input" name="gstin"></div><div class="ms-field ms-full"><label>Address</label><textarea class="ms-textarea" name="address"></textarea></div><div class="ms-field ms-full"><button class="ms-btn ms-btn-primary">Save Supplier</button></div></div></form></div></dialog>
<?= $this->endSection() ?>
