<?php
$gstEnabled=(bool)($cfg['gst_enabled']??false); $gstMode=$cfg['gst_mode']??'inclusive';
$color=preg_match('/^#[0-9a-fA-F]{6}$/',(string)($cfg['invoice_color']??'#e87523'))?($cfg['invoice_color']??'#e87523'):'#e87523';
$currency=$shop['currency']??'INR'; $money=$currency==='INR'?'₹':$currency.' ';
$img=function($base64,$mime){return $base64?'data:'.($mime?:'image/png').';base64,'.$base64:null;};
$logo=$img($shop['logo_base64']??null,$shop['logo_mime']??null); $signature=$img($shop['signature_base64']??null,$shop['signature_mime']??null);
?><!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:20mm 15mm}body{font-family:DejaVu Sans,sans-serif;color:#18202a;font-size:10px}.invoice{border:1px solid #ddd;padding:22px;--accent:<?=$color?>}.head{display:table;width:100%;border-bottom:2px solid var(--accent);padding-bottom:14px}.company{display:table-cell;width:65%;vertical-align:top}.logo{width:58px;height:58px;object-fit:contain;float:left;margin-right:12px}.company h1{font-size:20px;margin:0 0 5px}.muted{color:#68717b}.doc{display:table-cell;text-align:right;vertical-align:top}.title{color:var(--accent);font-size:18px;font-weight:bold}.party{margin:15px 0;padding:10px;border:1px solid #ddd;background:#f7f8fa}.label{color:var(--accent);font-size:8px;font-weight:bold;text-transform:uppercase}.table{width:100%;border-collapse:collapse}.table th,.table td{border-bottom:1px solid #ddd;padding:7px}.table th{background:#f3f4f6;text-align:left;font-size:8px}.num{text-align:right}.bottom{margin-top:18px;display:table;width:100%}.terms{display:table-cell;width:58%;vertical-align:top}.totals{display:table-cell;width:42%;vertical-align:top}.totals div{display:flex;justify-content:space-between;padding:4px}.grand{border-top:2px solid #18202a;font-size:13px;font-weight:bold}.footer{margin-top:25px;border-top:1px solid #ddd;padding-top:12px;display:table;width:100%}.sign{display:table-cell;text-align:right}.sign img{max-width:120px;max-height:50px}
</style></head><body><div class="invoice"><div class="head"><div class="company"><?php if($logo): ?><img class="logo" src="<?=$logo?>"><?php endif; ?><h1><?=esc($shop['name']??'Shop')?></h1><?php if(!empty($cfg['show_company_address'])&&$shop['address']): ?><div class="muted"><?=nl2br(esc($shop['address']))?></div><?php endif; ?><div class="muted"><?php if(!empty($cfg['show_company_phone'])&&$shop['phone']): ?><?=esc($shop['phone'])?> <?php endif; ?><?php if(!empty($cfg['show_company_email'])&&$shop['email']): ?><?=esc($shop['email'])?><?php endif; ?><?php if($gstEnabled&&$shop['gstin']): ?> GSTIN: <?=esc($shop['gstin'])?><?php endif; ?></div></div><div class="doc"><div class="title"><?=esc($cfg['title']??'INVOICE')?></div><strong><?=esc($sale['invoice_no'])?></strong><br>Date: <?=esc(date('d M Y',strtotime($sale['sale_date'])))?><?php if($sale['due_date']): ?><br>Due: <?=esc(date('d M Y',strtotime($sale['due_date'])))?><?php endif; ?></div></div>
<div class="party"><span class="label">Bill to</span><br><strong><?=esc($sale['customer_name'])?></strong><br><?=esc($sale['customer_phone']??'')?><?php if($sale['customer_email']): ?> · <?=esc($sale['customer_email'])?><?php endif; ?><?php if(!empty($cfg['show_customer_address'])&&$sale['customer_address']): ?><br><?=nl2br(esc($sale['customer_address']))?><?php endif; ?><?php if($gstEnabled&&!empty($cfg['show_customer_gstin'])&&$sale['customer_gstin']): ?><br>GSTIN: <?=esc($sale['customer_gstin'])?><?php endif; ?></div>
<table class="table"><thead><tr><th>#</th><th>Item</th><th class="num">Qty</th><th class="num">Rate</th><?php if(!empty($cfg['show_item_discount'])):?><th class="num">Discount</th><?php endif;?><?php if($gstEnabled):?><th class="num">GST</th><?php endif;?><th class="num">Amount</th></tr></thead><tbody><?php foreach($items as $i=>$it): ?><tr><td><?=($i+1)?></td><td><strong><?=esc($it['name'])?></strong><?php if($it['model']):?><br><span class="muted"><?=esc($it['model'])?></span><?php endif;?><?php if(!empty($cfg['show_hsn'])&&$it['hsn_sac']):?><br><span class="muted">HSN/SAC: <?=esc($it['hsn_sac'])?></span><?php endif;?></td><td class="num"><?=rtrim(rtrim(number_format((float)$it['qty'],3,'.',''),'0'),'.')?></td><td class="num"><?=$money.number_format((float)$it['unit_price'],2)?></td><?php if(!empty($cfg['show_item_discount'])):?><td class="num"><?=((float)$it['discount_amount']>0?'− ':'').$money.number_format((float)$it['discount_amount'],2)?></td><?php endif;?><?php if($gstEnabled):?><td class="num"><?=number_format((float)$it['tax_percent'],2)?>%</td><?php endif;?><td class="num"><strong><?=$money.number_format((float)$it['line_total'],2)?></strong></td></tr><?php endforeach;?></tbody></table>
<div class="bottom"><div class="terms"><?php if($cfg['terms']):?><span class="label">Terms & Conditions</span><p><?=nl2br(esc($cfg['terms']))?></p><?php endif;?></div><div class="totals"><div><span>Subtotal</span><strong><?=$money.number_format((float)$sale['subtotal'],2)?></strong></div><?php if((float)$sale['discount_total']>0):?><div><span>Discount</span><strong>− <?=$money.number_format((float)$sale['discount_total'],2)?></strong></div><?php endif;?><?php if($gstEnabled):?><div><span>GST<?= $gstMode==='inclusive'?' (included)':''?></span><strong><?=$money.number_format((float)$sale['tax_total'],2)?></strong></div><?php endif;?><div class="grand"><span>Grand Total</span><strong><?=$money.number_format((float)$sale['grand_total'],2)?></strong></div><div><span>Paid</span><strong><?=$money.number_format((float)$sale['paid_amount'],2)?></strong></div><div><span>Balance Due</span><strong><?=$money.number_format((float)$sale['due_amount'],2)?></strong></div></div></div>
<div class="footer"><div><?=esc($cfg['footer']??'Thank you for your business.')?></div><?php if(!empty($cfg['show_signature'])&&$signature):?><div class="sign"><img src="<?=$signature?>"><br>Authorized Signatory</div><?php endif;?></div></div></body></html>
